[2023-06-20T17:09:24.879+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run scheduled__2023-06-19T00:00:00+00:00 [queued]>
[2023-06-20T17:09:24.888+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run scheduled__2023-06-19T00:00:00+00:00 [queued]>
[2023-06-20T17:09:24.897+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T17:09:24.898+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-06-20T17:09:24.901+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T17:09:24.913+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-19 00:00:00+00:00
[2023-06-20T17:09:24.922+0000] {standard_task_runner.py:55} INFO - Started process 1257 to run task
[2023-06-20T17:09:24.927+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'dbt_run', 'scheduled__2023-06-19T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpa5k84txi']
[2023-06-20T17:09:24.933+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask dbt_run
[2023-06-20T17:09:25.391+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.dbt_run scheduled__2023-06-19T00:00:00+00:00 [running]> on host 997d3df41c0b
[2023-06-20T17:09:25.472+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-19T00:00:00+00:00
[2023-06-20T17:09:25.475+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-20T17:09:25.476+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'source $PATH_TO_DBT_VENV && dbt run --models .']
[2023-06-20T17:09:25.496+0000] {subprocess.py:86} INFO - Output:
[2023-06-20T17:09:25.500+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /usr/local/***/dbt_venv/bin/dbt: No such file or directory
[2023-06-20T17:09:25.503+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-20T17:09:25.526+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-20T17:09:25.533+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=dbt_run, execution_date=20230619T000000, start_date=20230620T170924, end_date=20230620T170925
[2023-06-20T17:09:25.553+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 8 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 1257)
[2023-06-20T17:09:25.631+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-20T17:09:25.652+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
