[2023-06-20T17:07:56.811+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run scheduled__2023-06-19T00:00:00+00:00 [queued]>
[2023-06-20T17:07:56.819+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run scheduled__2023-06-19T00:00:00+00:00 [queued]>
[2023-06-20T17:07:56.820+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T17:07:56.822+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 3
[2023-06-20T17:07:56.824+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T17:07:56.833+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-19 00:00:00+00:00
[2023-06-20T17:07:56.843+0000] {standard_task_runner.py:55} INFO - Started process 1169 to run task
[2023-06-20T17:07:56.848+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'dbt_run', 'scheduled__2023-06-19T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpb2rgmwgo']
[2023-06-20T17:07:56.851+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask dbt_run
[2023-06-20T17:07:57.192+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.dbt_run scheduled__2023-06-19T00:00:00+00:00 [running]> on host 997d3df41c0b
[2023-06-20T17:07:57.244+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-19T00:00:00+00:00
[2023-06-20T17:07:57.246+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-20T17:07:57.248+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'source $PATH_TO_DBT_VENV && dbt run --models .']
[2023-06-20T17:07:57.264+0000] {subprocess.py:86} INFO - Output:
[2023-06-20T17:07:57.269+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /usr/local/dbt_venv/bin/dbt: No such file or directory
[2023-06-20T17:07:57.271+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-20T17:07:57.283+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-20T17:07:57.290+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=dbt_run, execution_date=20230619T000000, start_date=20230620T170756, end_date=20230620T170757
[2023-06-20T17:07:57.302+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 7 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 1169)
[2023-06-20T17:07:57.351+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-20T17:07:57.370+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
