[2023-08-04T16:33:57.162+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-08-04T16:22:40.718335+00:00 [queued]>
[2023-08-04T16:33:57.170+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-08-04T16:22:40.718335+00:00 [queued]>
[2023-08-04T16:33:57.171+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T16:33:57.172+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 3
[2023-08-04T16:33:57.173+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T16:33:57.182+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-04 16:22:40.718335+00:00
[2023-08-04T16:33:57.189+0000] {standard_task_runner.py:55} INFO - Started process 920 to run task
[2023-08-04T16:33:57.194+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'manual__2023-08-04T16:22:40.718335+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmprkxjk0i_']
[2023-08-04T16:33:57.197+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask get_input_data
[2023-08-04T16:33:57.259+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-08-04T16:22:40.718335+00:00 [running]> on host 68b6c38d20d3
[2023-08-04T16:33:57.315+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-04T16:22:40.718335+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-04T16:22:40.718335+00:00
[2023-08-04T16:33:57.322+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T16:33:57.324+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T16:33:57.342+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T16:33:57.344+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-08-04T16:33:57.346+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-08-04T16:33:57.359+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-08-04T16:33:57.364+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230804T162240, start_date=20230804T163357, end_date=20230804T163357
[2023-08-04T16:33:57.376+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 6 for task get_input_data (Bash command failed. The command returned a non-zero exit code 127.; 920)
[2023-08-04T16:33:57.409+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-04T16:33:57.427+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
