[2023-08-04T17:07:22.943+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-08-04T17:07:20.696070+00:00 [queued]>
[2023-08-04T17:07:22.953+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-08-04T17:07:20.696070+00:00 [queued]>
[2023-08-04T17:07:22.954+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T17:07:22.955+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-08-04T17:07:22.956+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-04T17:07:22.971+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): get_input_data> on 2023-08-04 17:07:20.696070+00:00
[2023-08-04T17:07:22.980+0000] {standard_task_runner.py:55} INFO - Started process 114 to run task
[2023-08-04T17:07:22.999+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'get_input_data', 'manual__2023-08-04T17:07:20.696070+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpw8yll6t5']
[2023-08-04T17:07:23.054+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask get_input_data
[2023-08-04T17:07:23.229+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.get_input_data manual__2023-08-04T17:07:20.696070+00:00 [running]> on host 0988d73d4691
[2023-08-04T17:07:23.396+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=get_input_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-04T17:07:20.696070+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-04T17:07:20.696070+00:00
[2023-08-04T17:07:23.404+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-04T17:07:23.407+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "dbt run --select stg_ipflow_input_data --profiles-dir /opt/***/dbt/dbt_dsg_app --project-dir /opt/***/dbt/dbt_dsg_app  --target dev --vars '{'env': 'dev'}' "]
[2023-08-04T17:07:23.456+0000] {subprocess.py:86} INFO - Output:
[2023-08-04T17:07:23.468+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-08-04T17:07:23.486+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-08-04T17:07:23.504+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-08-04T17:07:23.517+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=get_input_data, execution_date=20230804T170720, start_date=20230804T170722, end_date=20230804T170723
[2023-08-04T17:07:23.548+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 6 for task get_input_data (Bash command failed. The command returned a non-zero exit code 127.; 114)
[2023-08-04T17:07:23.594+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-04T17:07:23.629+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
