[2023-06-20T20:55:40.358+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run manual__2023-06-20T20:54:11.483592+00:00 [queued]>
[2023-06-20T20:55:40.364+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run manual__2023-06-20T20:54:11.483592+00:00 [queued]>
[2023-06-20T20:55:40.365+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T20:55:40.366+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-06-20T20:55:40.368+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T20:55:40.378+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-20 20:54:11.483592+00:00
[2023-06-20T20:55:40.385+0000] {standard_task_runner.py:55} INFO - Started process 13625 to run task
[2023-06-20T20:55:40.390+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'dbt_run', 'manual__2023-06-20T20:54:11.483592+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpe76r90bj']
[2023-06-20T20:55:40.396+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask dbt_run
[2023-06-20T20:55:40.465+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.dbt_run manual__2023-06-20T20:54:11.483592+00:00 [running]> on host 635f1a4ac995
[2023-06-20T20:55:40.522+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-20T20:54:11.483592+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-20T20:54:11.483592+00:00
[2023-06-20T20:55:40.525+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-20T20:55:40.527+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'source /opt/***/dbt_venv/bin/dbt && cd /opt/***/dbt/dbt_dsg_app && dbt run --models .']
[2023-06-20T20:55:40.551+0000] {subprocess.py:86} INFO - Output:
[2023-06-20T20:55:40.558+0000] {subprocess.py:93} INFO - /opt/***/dbt_venv/bin/dbt: line 3: import: command not found
[2023-06-20T20:55:40.560+0000] {subprocess.py:93} INFO - /opt/***/dbt_venv/bin/dbt: line 4: import: command not found
[2023-06-20T20:55:40.561+0000] {subprocess.py:93} INFO - /opt/***/dbt_venv/bin/dbt: line 5: from: command not found
[2023-06-20T20:55:40.562+0000] {subprocess.py:93} INFO - /opt/***/dbt_venv/bin/dbt: line 7: syntax error near unexpected token `('
[2023-06-20T20:55:40.564+0000] {subprocess.py:93} INFO - /opt/***/dbt_venv/bin/dbt: line 7: `    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])'
[2023-06-20T20:55:40.565+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-06-20T20:55:40.580+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-06-20T20:55:40.588+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=dbt_run, execution_date=20230620T205411, start_date=20230620T205540, end_date=20230620T205540
[2023-06-20T20:55:40.602+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 16 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 13625)
[2023-06-20T20:55:40.651+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-20T20:55:40.671+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
