[2023-06-20T20:54:13.719+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run manual__2023-06-20T20:54:11.483592+00:00 [queued]>
[2023-06-20T20:54:13.739+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dbt_ipflow_dag.dbt_run manual__2023-06-20T20:54:11.483592+00:00 [queued]>
[2023-06-20T20:54:13.741+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T20:54:13.743+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-06-20T20:54:13.744+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-20T20:54:13.757+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-20 20:54:11.483592+00:00
[2023-06-20T20:54:13.767+0000] {standard_task_runner.py:55} INFO - Started process 13530 to run task
[2023-06-20T20:54:13.772+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_ipflow_dag', 'dbt_run', 'manual__2023-06-20T20:54:11.483592+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dbt_ip_flow_dag.py', '--cfg-path', '/tmp/tmpv_en3h_y']
[2023-06-20T20:54:13.776+0000] {standard_task_runner.py:83} INFO - Job 15: Subtask dbt_run
[2023-06-20T20:54:13.883+0000] {task_command.py:389} INFO - Running <TaskInstance: dbt_ipflow_dag.dbt_run manual__2023-06-20T20:54:11.483592+00:00 [running]> on host 635f1a4ac995
[2023-06-20T20:54:13.980+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_ipflow_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-20T20:54:11.483592+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-20T20:54:11.483592+00:00
[2023-06-20T20:54:13.985+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-20T20:54:13.987+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'source /opt/***/dbt_venv/bin/dbt && cd /opt/***/dbt/dbt_dsg_app && dbt run --models .']
[2023-06-20T20:54:14.006+0000] {subprocess.py:86} INFO - Output:
[2023-06-20T20:54:14.025+0000] {subprocess.py:93} INFO - /opt/***/dbt_venv/bin/dbt: line 3: import: command not found
[2023-06-20T20:54:14.030+0000] {subprocess.py:93} INFO - /opt/***/dbt_venv/bin/dbt: line 4: import: command not found
[2023-06-20T20:54:14.035+0000] {subprocess.py:93} INFO - /opt/***/dbt_venv/bin/dbt: line 5: from: command not found
[2023-06-20T20:54:14.038+0000] {subprocess.py:93} INFO - /opt/***/dbt_venv/bin/dbt: line 7: syntax error near unexpected token `('
[2023-06-20T20:54:14.040+0000] {subprocess.py:93} INFO - /opt/***/dbt_venv/bin/dbt: line 7: `    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])'
[2023-06-20T20:54:14.042+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-06-20T20:54:14.061+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-06-20T20:54:14.072+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dbt_ipflow_dag, task_id=dbt_run, execution_date=20230620T205411, start_date=20230620T205413, end_date=20230620T205414
[2023-06-20T20:54:14.094+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 15 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 13530)
[2023-06-20T20:54:14.145+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-20T20:54:14.168+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
